[package]
name = "delauny-triangulation-rust"
version = "0.1.0"
authors = ["sebastian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
draw="0.3.0"
rand="0.7.3"
